### ISSUE TITLE
Error thrown when installing protolint through yarn

### ISSUE THREAD

**Issue by cats256** [yoheimuta/protolint#362]
Original command is: yarn add protolint --dev
```
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > ts-node@10.9.2" has unmet peer dependency "@types/node@*".
[4/4] Building fresh packages...
[1/2] ⠐ protobufjs
error C:\Users\nhatt\Downloads\All\Code\web\node-grpc\node_modules\protolint: Command failed.
Exit code: 1
Command: node install.mjs
Arguments: 
Directory: C:\Users\nhatt\Downloads\All\Code\web\node-grpc\node_modules\protolint
Output:
file:///C:/Users/nhatt/Downloads/All/Code/web/node-grpc/node_modules/@sindresorhus/is/dist/index.js:322
        throw new TypeError(`Expected value which is \`${description}\`, ${valuesMessage}.`);
              ^

TypeError: Expected value which is `predicate returns truthy for any value`, received values of types `null`.
    at assertType (file:///C:/Users/nhatt/Downloads/All/Code/web/node-grpc/node_modules/@sindresorhus/is/dist/index.js:322:15)
    at Object.any (file:///C:/Users/nhatt/Downloads/All/Code/web/node-grpc/node_modules/@sindresorhus/is/dist/index.js:426:36)
    at set agent [as agent] (file:///C:/Users/nhatt/Downloads/All/Code/web/node-grpc/node_modules/got/dist/source/core/options.js:468:20)
    at Options.merge (file:///C:/Users/nhatt/Downloads/All/Code/web/node-grpc/node_modules/got/dist/source/core/options.js:411:27)
    at got.extend (file:///C:/Users/nhatt/Downloads/All/Code/web/node-grpc/node_modules/got/dist/source/create.js:82:25)
    at file:///C:/Users/nhatt/Downloads/All/Code/web/node-grpc/node_modules/protolint/install.mjs:34:22

Node.js v18.17.1
```

**Comment by yoheimuta** [comment]
@carstencodes Do you have any idea?
